version: 0.2

env:
  secrets-manager:
    DEPOT_TOKEN: "arn:aws:secretsmanager:us-west-2:412414942595:secret:depot-user-api-jIBXlU:DEPOT_TOKEN"
    WEBHOOK_API_KEY: "arn:aws:secretsmanager:us-west-2:412414942595:secret:depot-user-api-jIBXlU:WEBHOOK_API_KEY"
  variables:
    MACHINE_ID: ${MACHINE_ID}
    WEBHOOK_ENDPOINT: ${WEBHOOK_ENDPOINT}

phases:
  pre_build:
    commands:
      - ecr_stdin=$(aws ecr get-login-password --region us-west-2)
      - registry_auth=$(printf "AWS:$ecr_stdin" | openssl base64 -A)
      - mkdir $HOME/.docker
      - echo "{\"auths\":{\"412414942595.dkr.ecr.us-west-2.amazonaws.com\":{\"auth\":\"$registry_auth\"}}}" > $HOME/.docker/config.json
      - echo Installing Depot CLI...
      - curl -L https://depot.dev/install-cli.sh | DEPOT_INSTALL_DIR="/tmp/codebuild/bin" sh
  build:
    commands:
      - depot build -t $IMAGE_NAME --push --platform linux/amd64 --build-arg DEPS_JSON="$DEPS_JSON" .
  post_build:
    commands:
      - BUILD_ID=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)
      - |
        curl -X POST "$WEBHOOK_ENDPOINT" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $WEBHOOK_API_KEY" \
          -d "{\"machineID\":\"$MACHINE_ID\",\"buildID\":\"$BUILD_ID\",\"imageName\":\"$IMAGE_NAME\"}"
