version: 0.2

env:
  secrets-manager:
    DEPOT_TOKEN: "arn:aws:secretsmanager:us-west-2:412414942595:secret:depot-user-api-jIBXlU:DEPOT_TOKEN"

phases:
  pre_build:
    commands:
      - ecr_stdin=$(aws ecr get-login-password --region us-west-2)
      - registry_auth=$(printf "AWS:$ecr_stdin" | openssl base64 -A)
      - mkdir $HOME/.docker
      - echo "{\"auths\":{\"<your-registry-url>\":{\"auth\":\"$registry_auth\"}}}" > $HOME/.docker/config.json
      - echo Installing Depot CLI...
      - curl -L https://depot.dev/install-cli.sh | DEPOT_INSTALL_DIR="/tmp/codebuild/bin" sh
  build:
    commands:
      - depot build -t 412414942595.dkr.ecr.us-west-2.amazonaws.com/runpod-worker-comfy:latest --push --platform linux/amd64 --build-arg DEPS_JSON="$DEPS_JSON" .
